
add_newline = false
format = """$directory$character"""
right_format = """$all"""
command_timeout = 1000
palette = "cyberdream"

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[➜](bold green)'

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = false
style = 'bold blue'
symbol = " "

# Programming languages with Nerd Font icons and colors

[rust]
symbol = " "
style = "fg:peach"
format = '[$symbol($version)]($style)'

[lua]
symbol = " "
style = "fg:blue"
format = '[$symbol($version)]($style)'

[python]
symbol = " "
style = "fg:yellow"
format = '[$symbol($version)]($style)'

[nodejs]
symbol = " "
style = "fg:green"
format = '[$symbol($version)]($style)'

[java]
symbol = " "
style = "fg:red"
format = '[$symbol($version)]($style)'

[golang]
symbol = " "
style = "fg:teal"
format = '[$symbol($version)]($style)'

[c]
symbol = " "
style = "fg:sapphire"
format = '[$symbol($version)]($style)'

[cpp]
symbol = " "
style = "fg:lavender"
format = '[$symbol($version)]($style)'

[php]
symbol = " "
style = "fg:purple"
format = '[$symbol($version)]($style)'

[ruby]
symbol = " "
style = "fg:maroon"
format = '[$symbol($version)]($style)'

[perl]
symbol = " "
style = "fg:flamingo"
format = '[$symbol($version)]($style)'

[elixir]
symbol = " "
style = "fg:pink"
format = '[$symbol($version)]($style)'

[erlang]
symbol = " "
style = "fg:subtext1"
format = '[$symbol($version)]($style)'

[scala]
symbol = " "
style = "fg:red"
format = '[$symbol($version)]($style)'

[swift]
symbol = " "
style = "fg:orange"
format = '[$symbol($version)]($style)'

[dart]
symbol = " "
style = "fg:sky"
format = '[$symbol($version)]($style)'

[haskell]
symbol = " "
style = "fg:mauve"
format = '[$symbol($version)]($style)'

[typescript]
symbol = " "
style = "fg:blue"
format = '[$symbol($version)]($style)'

[kotlin]
symbol = " "
style = "fg:lavender"
format = '[$symbol($version)]($style)'

[dotnet]
symbol = " "
style = "fg:text"
format = '[$symbol($version)]($style)'

# Docker and Kubernetes
[docker_context]
disabled = true

[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
]

# Cyberdream color palette
[palettes.cyberdream]
peach = "#f4a261"
blue = "#82aaff"
yellow = "#f2cc81"
green = "#a3be8c"
teal = "#5fb3b3"
sapphire = "#57c7ff"
lavender = "#b4befe"
pink = "#ff79c6"
red = "#ec5f67"
maroon = "#c678dd"
purple = "#c792ea"
flamingo = "#ff5370"
sky = "#89dceb"
text = "#d0d0d0"
subtext1 = "#a0a0a0"
overlay2 = "#7f849c"
overlay1 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#2e2e3e"
base = "#1c1c24"
mantle = "#1a1b26"
crust = "#16161e"
